language: python

script: python setup.py test

jobs:
  include:
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: test
      python: 3.6
    - stage: Pypi Upload
      script: echo "Uploading packages to Pypi"
      deploy:
        provider: pypi
        user: felipaoo
        on:
          tags: true
        password:
          secure: "rdO2c9Dk7z4IQuCIm75p/E0zRaQs78HD8fRrGiav9UhxQY+BCKsi6jemuNusFY0SGCADlRQBzazcHyi9hNOtDJcuthK9rQ7p/qZi/6PZuPj1k+o//ng4KqjQLj/6XS+uuli4s7fDh7tJOr4dceqIRVNco94wyDXB2YVB4MhvCHcoqqyj+PHnIWObssRr5OwDyGltWUMJKFdg4UKai52rQrfKg7dgF9JEVboND/4PPn1WEI2ejPWs1whbtbB6B1tN25T3IStdWvcm3QJCDekyfEzNUYnlUjBjF979HrhaiGvVH9DV2giIrJr3wK/+wAp73NW/0S385BCx+j/1U7UZ2aZykENLDVq+mvECFq85cXMHrdlZY8B+fDmy5hPcmrgrFrf4Kh/+9WCXwQMpz2liTuUkF69QInBXwxxmxXYO91DUQyZQO9nifZQVvZ8eVueOiV6+vDAWYMdPyxzcUxqOsH/h8GAytyZhjeMNwv5vtA5bB5GsSzgI9QAP30X++EGYF/Jw69jJa6YTykRBnXXBF1h0LWhqPmA8w83kQEB2gOByPOzA879IgGf49Veh7MFU4Mz4SnTJlvXuLs4tuGQcIh9Nxhvr25Io8FxCHv6aUb+yDlJ7Bdxc2Q9qnZieMKA0mjIUpHkTjgBfi2jQZ1tdMbc6ZBlUEAV0fn+dQc3Wesk="
        server: https://test.pypi.org/legacy/
        distributions: sdist bdist_wheel
